_wandb:
    value:
        cli_version: 0.21.0
        e:
            r5m1j88wzt6a2gch3oakjo6bwy5oqw76:
                args:
                    - --config
                    - /workspace/demo/Odyssey/configs/FSQ_STAGE_1_FINAL.yaml
                    - --use-wandb
                codePath: odyssey/train/train_fsdp.py
                codePathLocal: train_fsdp.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "32212254720"
                        used: "996737024"
                email: connor@anthrogen.com
                executable: /usr/bin/python
                git:
                    commit: ef29ef517ee69f94539b2616bdb8560fd9425595
                    remote: git@github.com:Anthrogen/Odyssey.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-bca18034-2b11-0f76-1078-c23935e0b8f6
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-d2bd9bf2-7f1b-55b6-32dd-068269de88c0
                host: 13b691ab70bf
                memory:
                    total: "2164115542016"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /workspace/demo/Odyssey/odyssey/train/train_fsdp.py
                python: CPython 3.11.11
                root: /workspace/demo/Odyssey/odyssey/train
                startedAt: "2025-07-20T14:15:15.914049Z"
                writerId: r5m1j88wzt6a2gch3oakjo6bwy5oqw76
        m:
            - "1": batch/train_seq_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": step
              "6":
                - 3
              "7": []
            - "1": model/val_loss_seq
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/train_rmsd
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/train_loss_seq
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/train_loss_struct
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/train_struct_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": model/val_rmsd
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": model/val_loss_struct
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": model/val_seq_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": model/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": model/val_struct_acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 7
                - 15
                - 16
            "4": 3.11.11
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
checkpoint_save_freq:
    value: null
model_0_batch_size:
    value: 4
model_0_d_model:
    value: 128
model_0_first_block:
    value: Self Consensus
model_0_mask_config:
    value: discrete_diffusion
model_0_max_epochs:
    value: 50
model_0_max_len:
    value: 2048
model_0_n_heads:
    value: 1
model_0_n_layers:
    value: 3
model_0_style:
    value: stage_1
num_models:
    value: 1
world_size:
    value: 2
