# Configuration for FSQ Stage 2 training
# Fine-tunes with pre-trained FSQ encoder using no masking

# =============================================================================
# Model Configuration
# =============================================================================
model:
  style: "stage_2"
  
  # Core transformer parameters
  d_model: 128
  n_heads: 1
  n_layers: 3
  max_len: 2048
  dropout: 0.1
  ff_mult: 4
  reference_model_seed: 42
  
  # Block type for first transformer block
  block_type: "self_consensus"
  
  # Block-specific parameters
  block_params:
    num_iterations: 1
    connectivity_type: "local_window"
    w: 2
    r: 8
    edge_hidden_dim: 24
  
  # FSQ parameters
  fsq:
    latent_dim: 32
    levels: [7, 5, 5, 5, 5]
    encoder_path: "checkpoints/fsq/SC_stage_1_discrete_diffusion_model.pt"

# =============================================================================
# Training Configuration
# =============================================================================
training:
  batch_size: 4
  max_epochs: 1
  learning_rate: 1e-5
  
  # Data paths
  data_dir: "sample_data/1k"
  checkpoint_dir: "checkpoints/fsq"

# =============================================================================
# Loss Configuration
# =============================================================================
loss:
  type: "kabsch_rmsd"

# =============================================================================
# Masking Configuration
# =============================================================================
masking:
  strategy: "none"