# Configuration for FSQ Stage 1 training
# Trains FSQ encoder from scratch using Kabsch RMSD loss

model_cfg:
  type: "fsq_cfg"
  params:
    style: "stage_1"
    d_model: 128
    n_heads: 1
    n_layers: 3
    max_len: 2048
    dropout: 0.1
    ff_mult: 4
    reference_model_seed: 42
    
    first_block_cfg:
      type: "self_attention_cfg"
      params: {}
    
    latent_dim: 32
    fsq_levels: [7, 5, 5, 5, 5]
    fsq_encoder_path: null

train_cfg:
  type: "training_cfg"
  params:
    batch_size: 4
    max_epochs: 50
    learning_rate: 1e-5
    data_dir: "sample_data/1k"
    checkpoint_dir: "checkpoints/fsq"
    
    loss_config:
      type: "kabsch_rmsd_loss_cfg"
      params: {}
    
    mask_config:
      type: "simple_mask_cfg"
      params:
        mask_prob_seq: 0.15
        mask_prob_struct: 0.15